name: tests
on:
  - push
  - pull_request
jobs:
  test-with-tox:
    name: Test with tox
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          - ubuntu-18.04
          - ubuntu-20.04  # ubuntu-latest
          - ubuntu-22.04
          - macos-10.15
          - macos-11  # macos-latest
          - macos-12
          - windows-2019
          - windows-2022  # windows-latest
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install libsndfile for linux
      if: matrix.platform == 'ubuntu-18.04' || matrix.platform == 'ubuntu-20.04' || matrix.platform == 'ubuntu-22.04'
      run: sudo apt-get install -y libsndfile1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Prepare code coverage data
      if: matrix.platform == 'ubuntu-22.04' && matrix.python-version == 3.9
      run: |
        # For NumPy 1.24+ compatibility, see: https://github.com/pytorch/pytorch/pull/91517
        pip install --pre torch==2.0.0.dev20230225 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install pandas tensorflow torch tensorboardX pillow matplotlib soundfile pytest pytest-cov
        pytest --doctest-glob="*.rst" --cov=./ --cov-report xml --ignore="tests/test_summary_reader/test_no_tensorflow.py"
    - name: Test documentation
      if: matrix.platform == 'ubuntu-22.04' && matrix.python-version == 3.9
      run: |
        sudo apt-get install -y pandoc
        # For NumPy 1.24+ compatibility, see: https://github.com/pytorch/pytorch/pull/91517
        pip install --pre torch==2.0.0.dev20230225 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install -r requirements.txt
        sphinx-build -b html docs docs/_build/html
        sphinx-build -b doctest docs docs/_build/doctest
    - name: Upload coverage to Codecov
      if: matrix.platform == 'ubuntu-22.04' && matrix.python-version == 3.9
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
