name: tests
on:
  - push
  - pull_request
jobs:
  test-with-tox:
    name: Test with tox
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          - ubuntu-18.04
          - ubuntu-latest  # ubuntu-20.04
          - macos-latest  # macOS-10.15
          - windows-2016
          - windows-latest  # windows-2019
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox